import { useEffect, useState } from 'react'
import './Admin.css'

const groups = [
  ['OVERVIEW', [['Overview', '/admin']]],
  ['PEOPLE', [['Careers', '/admin/careers'], ['Applications', '/admin/applications'], ['Candidates', '/admin/candidates'], ['Teams', '/admin/teams']]],
  ['CONTENT', [['Website Content', '/admin/content'], ['Insights', '/admin/insights'], ['Media', '/admin/media']]],
  ['TECHNOLOGY', [['AI Research', '/admin/research'], ['R&D', '/admin/rd'], ['Projects', '/admin/projects']]],
  ['BUSINESS', [['Contacts', '/admin/contacts'], ['Services', '/admin/services']]],
  ['ANALYTICS', [['Analytics', '/admin/analytics'], ['Reports', '/admin/reports']]],
  ['SYSTEM', [['Notifications', '/admin/notifications'], ['Activity Log', '/admin/activity'], ['Settings', '/admin/settings']]],
]
const copy = { applications: ['Applications', 'Review incoming candidates and move them through the hiring process.'], candidates: ['Candidates', 'Candidate profiles and recruitment activity will appear here when connected.'], teams: ['Teams', 'Organize the people responsible for careers, research, delivery, and operations.'], content: ['Website Content', 'Manage public page and navigation status from one editorial workspace.'], insights: ['Insights', 'Publish and maintain research-led perspectives for the public site.'], media: ['Media Library', 'Images, videos, documents, logos, and brand assets.'], research: ['AI Research', 'Track research publications, experiments, prototypes, and validation.'], rd: ['R&D', 'Manage research projects and technology studies.'], projects: ['Projects', 'Track implementation from planning through production.'], contacts: ['Contacts', 'Review contact enquiries and business conversations.'], services: ['Services', 'Manage the services presented across the MENTNEO experience.'], analytics: ['Analytics', 'Connected analytics and reporting for the administration workspace.'], reports: ['Reports', 'Analytics reports become available when a connected source exists.'], notifications: ['Notifications', 'System and workflow notifications for administrators.'], activity: ['Activity Log', 'A record of administrative actions and system events.'], settings: ['Settings', 'Account, security, notifications, website, brand, content, permissions, and system settings.'] }

function Login() {
  const [identity, setIdentity] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(false); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identity, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (remember) localStorage.setItem('mentneo_admin_identity', identity); else localStorage.removeItem('mentneo_admin_identity'); window.location.href = '/admin' } catch { setError('Sign in failed. Check your credentials and try again.') } finally { setBusy(false) } }
  useEffect(() => { setIdentity(localStorage.getItem('mentneo_admin_identity') || '') }, [])
  return <main className="admin-login"><div className="login-brand"><span className="admin-mark">M</span><strong>MENTNEO</strong><small>AI RESEARCH &amp; DEVELOPMENT</small></div><div className="login-copy"><span className="admin-kicker">PRIVATE TECHNOLOGY COMMAND CENTER</span><h1>Admin<br /><em>Control Center.</em></h1><p>Secure access to the MENTNEO administration environment.</p></div><form className="login-form" onSubmit={submit}><label>Email / Username<input autoComplete="username" value={identity} onChange={(event) => setIdentity(event.target.value)} required /></label><label>Password<div className="password-field"><input autoComplete="current-password" type={visible ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} required /><button type="button" onClick={() => setVisible(!visible)}>{visible ? 'Hide' : 'Show'}</button></div></label>{error && <p className="admin-error">{error}</p>}<div className="login-options"><label><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /> Remember Me</label><button type="button" className="text-button">Forgot Password</button></div><button className="admin-primary login-submit" disabled={busy}>{busy ? 'Signing In...' : 'Sign In'} <span>â†—</span></button><small className="login-config">Credentials are configured by the server.</small></form></main>
}
function Badge({ children, tone = '' }) { return <span className={`status-badge ${tone}`}>{children}</span> }
function Sidebar({ path }) { return <aside className="admin-sidebar"><a className="admin-brand" href="/admin"><span className="admin-mark">M</span><span>MENTNEO<small>ADMIN CONTROL CENTER</small></span></a><nav>{groups.map(([group, items]) => <div className="sidebar-group" key={group}><span className="sidebar-label">{group}</span>{items.map(([label, href]) => <a className={path === href || (href !== '/admin' && path.startsWith(href)) ? 'active' : ''} href={href} key={label}><i>{label.slice(0, 1)}</i>{label}</a>)}</div>)}</nav><div className="sidebar-bottom"><div className="admin-status"><i /> System status <b>NOT CONNECTED</b></div><span>Admin Account<br /><strong>Workspace owner</strong></span><button className="logout-button" onClick={async () => { await fetch('/api/auth/logout', { method: 'POST' }); window.location.href = '/admin/login' }}>Logout <span>â†—</span></button></div></aside> }
function Header({ title, description, onSearch }) { return <header className="admin-topbar"><div><span className="admin-breadcrumb">MENTNEO / ADMIN / {title.toUpperCase()}</span><h1>{title}</h1><p>{description}</p></div><div className="header-tools"><button onClick={onSearch}>âŒ• <span>Search</span><kbd>âŒ˜ K</kbd></button><button>â—Œ<i>3</i></button><span className="admin-avatar">MN</span></div></header> }
function Empty({ text = 'This module is ready for a connected data source. No information is being fabricated here.' }) { return <div className="admin-empty"><span>â€”</span><strong>Not connected yet</strong><p>{text}</p><button className="admin-secondary">Review connection</button></div> }
function Stats({ jobs }) { const live = jobs.filter((job) => job.status === 'published' && !job.closed).length; return <section className="metric-grid">{[['Active Careers', live.toString().padStart(2, '0'), 'Visible on public careers'], ['Applications', 'NOT CONNECTED', 'No connected source'], ['Candidates', 'NOT CONNECTED', 'No connected source'], ['Projects', 'NOT CONNECTED', 'No connected source'], ['Research', 'NOT CONNECTED', 'No connected source'], ['Insights', 'NOT CONNECTED', 'No connected source'], ['Contacts', 'NOT CONNECTED', 'No connected source'], ['Website Views', 'NOT CONNECTED', 'Analytics not connected']].map(([label, value, note]) => <article className={label === 'Applications' ? 'stat-card accent' : 'stat-card'} key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section> }
function Overview({ jobs, onAdd }) { return <><Stats jobs={jobs} /><div className="overview-columns"><section className="admin-panel"><div className="panel-heading"><div><span className="admin-kicker">SYSTEM STATUS</span><h2>Operational readiness</h2></div><Badge>NOT CONNECTED</Badge></div>{['Website', 'Admin API', 'Database', 'Authentication', 'Content System'].map((item) => <div className="system-row" key={item}><span>{item}</span><Badge>NOT CONNECTED</Badge></div>)}</section><section className="admin-panel"><div className="panel-heading"><div><span className="admin-kicker">WORKSPACE</span><h2>Quick Actions</h2></div></div>{[['Add Career', '/admin/careers'], ['Add Insight', '/admin/insights'], ['Add Research', '/admin/research'], ['Add Project', '/admin/projects'], ['Add Team Member', '/admin/teams'], ['Upload Media', '/admin/media']].map(([label, href]) => <a className="quick-action" href={href} onClick={label === 'Add Career' ? onAdd : undefined} key={label}>ï¼‹ {label}<b>â†—</b></a>)}</section></div></> }
function Careers({ jobs, reload, loading, onAdd }) { const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All roles'); const [confirm, setConfirm] = useState(null); const visible = jobs.filter((job) => `${job.title} ${job.department} ${job.location}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All roles' || filter === (job.closed ? 'Closed' : job.status === 'published' ? 'Published' : 'Drafts'))); const update = async (job, changes) => { await fetch(`/api/jobs/${job.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); reload() }; const remove = async () => { await fetch(`/api/jobs/${confirm.id}`, { method: 'DELETE' }); setConfirm(null); reload() }; return <><div className="module-toolbar"><div><span className="admin-kicker">HIRING WORKSPACE</span><p>Keep open roles accurate, visible, and moving.</p></div><button className="admin-primary" onClick={onAdd}>ï¼‹ Add Career</button></div><div className="mini-tabs">{['All roles', 'Published', 'Drafts', 'Closed'].map((item) => <button className={filter === item ? 'selected' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><section className="admin-panel table-panel"><div className="table-tools"><label className="admin-search">âŒ• <input placeholder="Search roles, teams, locations" value={query} onChange={(event) => setQuery(event.target.value)} /></label><button className="admin-secondary" onClick={reload}>Refresh</button></div>{loading ? <div className="loading-state">Loading roles...</div> : <div className="data-table"><div className="table-row table-head"><span>Role</span><span>Team</span><span>Location</span><span>Deadline</span><span>Status</span><span>Actions</span></div>{visible.map((job) => { const status = job.closed ? 'Closed' : job.status === 'published' ? 'Published' : 'Draft'; return <div className="table-row" key={job.id}><strong>{job.title}</strong><span>{job.department}</span><span>{job.location}</span><span>{job.deadline || 'No deadline'}</span><Badge tone={status.toLowerCase()}>{status}</Badge><div className="table-actions"><button onClick={() => update(job, { status: job.status === 'published' ? 'draft' : 'published' })}>{job.status === 'published' ? 'Unpublish' : 'Publish'}</button><button onClick={() => update(job, { closed: !job.closed })}>{job.closed ? 'Reopen' : 'Close'}</button><button className="danger" onClick={() => setConfirm(job)}>Delete</button></div></div> })}{!visible.length && <Empty text="Create a role or adjust your filters." />}</div>}</section>{confirm && <div className="confirm-backdrop"><div className="confirm-dialog"><span className="admin-kicker">CONFIRM ACTION</span><h2>Delete {confirm.title}?</h2><p>This action permanently removes the role from the jobs data.</p><button className="admin-secondary" onClick={() => setConfirm(null)}>Cancel</button><button className="danger-button" onClick={remove}>Delete</button></div></div>}</> }
function AddCareer({ close, created }) { const [form, setForm] = useState({ title: '', department: 'Engineering', location: '', type: 'Full-time', deadline: '' }); const submit = async (event) => { event.preventDefault(); await fetch('/api/jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); created() }; return <div className="confirm-backdrop"><form className="career-modal" onSubmit={submit}><button type="button" className="dialog-close" onClick={close}>Ã—</button><span className="admin-kicker">NEW CAREER</span><h2>Add a career</h2><p>Create a draft first, then publish it when ready.</p>{[['title', 'Role title'], ['location', 'Location'], ['deadline', 'Application deadline']].map(([name, label]) => <label key={name}>{label}<input required value={form[name]} onChange={(event) => setForm({ ...form, [name]: event.target.value })} /></label>)}<div className="form-two"><label>Department<select value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })}>{['Engineering', 'AI Research', 'Data Intelligence', 'Growth', 'Marketing', 'People'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{['Full-time', 'Part-time', 'Internship', 'Contract'].map((item) => <option key={item}>{item}</option>)}</select></label></div><button className="admin-primary">Create Draft <span>â†—</span></button></form></div> }
function Generic({ section }) { const [title, description] = copy[section] || ['Admin Module', 'This module is ready to be configured.']; return <section className="admin-panel module-empty"><div className="panel-heading"><div><span className="admin-kicker">MODULE</span><h2>{title}</h2></div><Badge>NOT CONNECTED</Badge></div><p>{description}</p><Empty /></section> }
function AdminPage({ path = '/admin' }) { const [user, setUser] = useState(null); const [authLoading, setAuthLoading] = useState(true); const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(false); const [search, setSearch] = useState(false); const [add, setAdd] = useState(false); const section = path === '/admin' ? 'overview' : path.split('/')[2] || 'overview'; const title = section === 'overview' ? 'Overview' : copy[section]?.[0] || 'Admin Control Center'; const description = section === 'overview' ? 'A clear view of MENTNEO operations, content, and system readiness.' : copy[section]?.[1] || 'Manage this workspace from the private control center.'; const reload = async () => { setLoading(true); try { const response = await fetch('/api/jobs'); if (response.ok) setJobs((await response.json()).jobs || []) } finally { setLoading(false) } }; useEffect(() => { if (path === '/admin/login') return setAuthLoading(false); fetch('/api/auth/me').then((response) => response.ok ? response.json() : Promise.reject()).then((data) => setUser(data.user)).catch(() => setUser(null)).finally(() => setAuthLoading(false)) }, [path]); useEffect(() => { if (user) reload() }, [user]); if (path === '/admin/login') return <Login />; if (authLoading) return <main className="admin-loading"><span className="admin-mark">M</span><p>Authenticating workspace...</p></main>; if (!user) { window.location.href = '/admin/login'; return null } return <main className="admin-console"><Sidebar path={path} /><section className="admin-main"><Header title={title} description={description} onSearch={() => setSearch(true)} /><div className="admin-content">{section === 'overview' ? <Overview jobs={jobs} onAdd={() => setAdd(true)} /> : section === 'careers' ? <Careers jobs={jobs} reload={reload} loading={loading} onAdd={() => setAdd(true)} /> : <Generic section={section} />}</div></section>{search && <div className="search-overlay"><div className="search-dialog"><button onClick={() => setSearch(false)}>Ã—</button><span className="admin-kicker">GLOBAL SEARCH</span><h2>Find in MENTNEO</h2><input autoFocus placeholder="Search admin modules..." />{['Careers', 'Applications', 'Candidates', 'Insights', 'Research', 'Projects', 'Contacts'].map((item) => <a href={`/admin/${item.toLowerCase()}`} key={item}>{item}<span>â†—</span></a>)}</div></div>}{add && <AddCareer close={() => setAdd(false)} created={() => { setAdd(false); reload() }} />}</main> }
export default AdminPage
