import { useEffect } from 'react'
import { InternalNavigation } from './App.jsx'
import './SoftwareDevelopment.css'

const caseStudies = [
  { date: 'Aug 26, 2026', title: 'AI-Powered Business Transformation', description: 'A practical study of how AI, automation, and intelligent workflows can transform business operations, reduce repetitive work, and improve decision-making.', slug: 'ai-powered-business-transformation', problem: 'Manual operations and disconnected workflows slowed decisions and consumed team capacity.', approach: 'Mapped the operational journey, then introduced focused automation and intelligent workflow orchestration.', technology: 'AI agents, workflow automation, business intelligence, and integrated APIs.', implementation: 'Connected the new system to existing business tools and introduced it in measured stages.', results: 'Reduced repetitive work and gave teams faster access to operational insight.', learnings: 'Useful transformation begins with the operating problem, not a generic technology layer.' },
  { date: 'Aug 20, 2026', title: 'Intelligent Customer Experience', description: 'Exploring the implementation of AI-powered customer support, conversational systems, personalization, and automated customer interactions.', slug: 'intelligent-customer-experience', problem: 'Customers needed faster, more consistent support across multiple interaction channels.', approach: 'Combined conversational intelligence with grounded knowledge and clear escalation paths.', technology: 'Conversational AI, knowledge retrieval, analytics, and customer-system integrations.', implementation: 'Deployed assisted interactions first, followed by carefully scoped autonomous workflows.', results: 'Improved response consistency while preserving human support for complex requests.', learnings: 'Trust grows when automation remains contextual, transparent, and easy to hand off.' },
  { date: 'Aug 15, 2026', title: 'Enterprise Workflow Automation', description: 'A case study examining how intelligent automation can connect business applications, workflows, APIs, data, and operational processes.', slug: 'enterprise-workflow-automation', problem: 'Critical work moved through disconnected applications and manual handoffs.', approach: 'Designed a connected workflow layer around the highest-value operational paths.', technology: 'APIs, event-driven workflows, automation agents, and operational data systems.', implementation: 'Integrated existing applications incrementally with monitoring at each handoff.', results: 'Made process ownership clearer and reduced avoidable manual coordination.', learnings: 'Enterprise automation succeeds when integration and observability are designed together.' },
  { date: 'Aug 10, 2026', title: 'Data Intelligence in Business', description: 'Exploring how analytics, AI, predictive models, and intelligent data systems can transform raw business data into actionable insights.', slug: 'data-intelligence-in-business', problem: 'Business data existed in separate systems without a shared path to decisions.', approach: 'Established a dependable data foundation and focused insight delivery around real decisions.', technology: 'Analytics pipelines, predictive models, semantic search, and decision support.', implementation: 'Unified selected data sources and delivered insights through existing working rhythms.', results: 'Turned scattered information into timely signals for operational planning.', learnings: 'Data intelligence becomes valuable when it reaches the decision at the right moment.' },
  { date: 'Aug 5, 2026', title: 'AI Voice Automation', description: 'A practical study of Voice AI systems used for customer conversations, service automation, appointment handling, and business communication.', slug: 'ai-voice-automation', problem: 'High-volume conversations required consistent handling beyond available team capacity.', approach: 'Built voice workflows around intent, context, safe actions, and human escalation.', technology: 'Speech recognition, voice generation, conversational AI, and service integrations.', implementation: 'Started with appointment and information flows before expanding the action set.', results: 'Handled routine conversations consistently while routing exceptions to people.', learnings: 'Voice automation depends as much on conversation design as model capability.' },
  { date: 'Aug 1, 2026', title: 'Custom AI Systems', description: 'Exploring the development of domain-specific AI systems designed around unique business requirements, workflows, knowledge, and operational challenges.', slug: 'custom-ai-systems', problem: 'Off-the-shelf tools could not represent the organization\'s specific knowledge and workflows.', approach: 'Researched the domain deeply and shaped a focused system around verified requirements.', technology: 'Custom AI models, knowledge systems, agents, and private application infrastructure.', implementation: 'Prototyped the highest-value capability, tested it with users, and expanded carefully.', results: 'Created a more relevant system aligned with the organization\'s actual work.', learnings: 'Custom technology earns its complexity when it solves a problem generic tools cannot.' },
]

function ResearchStatus({ status }) { return <span className="software-status">{status}</span> }
function ResearchHeader() { return <div className="software-research-header"><span className="section-label">CASE STUDIES</span><h1>Technology in<br /><em>Practice.</em></h1><p>Exploring real-world applications, implementations, experiments, and outcomes across AI, software, automation, data, and digital technologies.</p></div> }
function ResearchItem({ entry }) { return <article className="software-research-item"><div className="software-research-meta"><span>Case Studies</span><time>{entry.date}</time></div><div className="software-research-copy"><a href={`/case-studies/${entry.slug}`}><h2>{entry.title}</h2><p>{entry.description}</p><ResearchStatus status="Published" /></a></div></article> }
function ResearchList() { return <div className="software-research-list" id="publications">{caseStudies.map((entry) => <ResearchItem entry={entry} key={entry.slug} />)}</div> }
function CaseStudyDetail({ entry }) { const fields = [['Problem', entry.problem], ['Approach', entry.approach], ['Technology', entry.technology], ['Implementation', entry.implementation], ['Results', entry.results], ['Key Learnings', entry.learnings]]; return <section className="software-detail case-detail"><span className="section-label">CASE STUDIES / PUBLISHED</span><h1>{entry.title}</h1><p>{entry.description}</p><ResearchStatus status="Published" /><div className="case-detail-fields">{fields.map(([label, text]) => <div key={label}><span>{label}</span><p>{text}</p></div>)}</div><a className="button button-ghost" href="/case-studies">Back to Case Studies <span>↗</span></a></section> }

function CaseStudiesPage({ path = '/case-studies' }) {
  useEffect(() => {
    const companyButton = [...document.querySelectorAll('.site-header .nav-item')].find((button) => button.textContent.trim().startsWith('Company'))
    companyButton?.classList.add('active')
    return () => companyButton?.classList.remove('active')
  }, [])
  const entry = caseStudies.find((item) => item.slug === path.split('/')[2])
  return <main className="rd-lab-page software-page case-page"><InternalNavigation /><section className="software-shell"><nav className="rd-lab-categories" aria-label="Publication categories">{['All', 'Publication', 'Conclusion', 'Milestone', 'Release'].map((category, index) => <a className={index === 0 ? 'active' : ''} href="#publications" key={category}>{category}</a>)}</nav><ResearchHeader />{entry ? <CaseStudyDetail entry={entry} /> : <ResearchList />}</section></main>
}

export default CaseStudiesPage
