import { useEffect } from 'react'
import { InternalNavigation } from './App.jsx'
import './SoftwareDevelopment.css'
import './Education.css'

const entries = [
  { date: 'Aug 26, 2026', title: 'Connected Education Systems', description: 'Designing connected digital education platforms that bring students, teachers, institutions, parents and administrators into one technology ecosystem.', status: 'Research', slug: 'connected-education-systems' },
  { date: 'Aug 20, 2026', title: 'AI-Powered Learning', description: 'Exploring AI-assisted learning experiences, personalized educational content, intelligent assistance, learning recommendations and student support.', status: 'AI Research', slug: 'ai-powered-learning' },
  { date: 'Aug 15, 2026', title: 'Digital Learning Platforms', description: 'Developing modern web and mobile learning environments for courses, educational content, communication, assessments and student engagement.', status: 'Prototype', slug: 'digital-learning-platforms' },
  { date: 'Aug 10, 2026', title: 'Learning Automation', description: 'Exploring automation for assignments, notifications, reminders, assessments, administrative workflows, communication and repetitive educational processes.', status: 'Automation', slug: 'learning-automation' },
  { date: 'Aug 5, 2026', title: 'Education Analytics', description: 'Researching learning analytics, student performance, engagement, attendance, course performance and institutional business intelligence.', status: 'Intelligence', slug: 'education-analytics' },
  { date: 'Aug 1, 2026', title: 'Personalized Education', description: 'Exploring adaptive learning, personalized recommendations, learning pathways and AI-assisted educational experiences based on learner requirements and available data.', status: 'Development', slug: 'personalized-education' },
]
const architecture = ['STUDENTS / TEACHERS / PARENTS / ADMIN', 'WEB / MOBILE PLATFORM', 'AUTHENTICATION', 'EDUCATION PLATFORM', 'COURSES / CONTENT / ASSESSMENTS', 'AI / AUTOMATION LAYER', 'STUDENT / LEARNING DATA', 'ANALYTICS & BI', 'INSTITUTIONAL INSIGHTS', 'MANAGEMENT']
const learningJourney = ['STUDENT REGISTRATION', 'PROFILE CREATION', 'COURSE / PROGRAM SELECTION', 'LEARNING CONTENT', 'AI LEARNING ASSISTANCE', 'ASSIGNMENTS / ASSESSMENTS', 'PROGRESS TRACKING', 'PERSONALIZED RECOMMENDATIONS', 'TEACHER INTERACTION', 'LEARNING ANALYTICS', 'CONTINUOUS IMPROVEMENT']
const automation = ['EDUCATION EVENT', 'BUSINESS RULES', 'WORKFLOW ENGINE', 'AUTOMATION', 'NOTIFICATION / TASK', 'STATUS UPDATE', 'ANALYTICS']
const analytics = ['STUDENT / COURSE DATA', 'DATA PROCESSING', 'CENTRAL DATA LAYER', 'ANALYTICS / BI', 'REPORTS / DASHBOARDS', 'EDUCATIONAL DECISIONS']
const platform = ['STUDENTS / TEACHERS / PARENTS', 'WEB / MOBILE APPLICATIONS', 'API LAYER', 'EDUCATION PLATFORM', 'DATABASE', 'AI / AUTOMATION', 'ANALYTICS']
const integration = ['EDUCATION PLATFORM', 'API LAYER', 'INTEGRATION LAYER', 'EXTERNAL SERVICES', 'INSTITUTIONAL SYSTEMS']

function StatusLabel({ status }) { return <span className="software-status">{status}</span> }
function ResearchHeader() { return <div className="software-research-header education-header"><span className="section-label">EDUCATION</span><h1>Technology, AI<br /><em>&amp; Digital Learning.</em></h1><p>Building connected education systems that improve learning, teaching, student engagement, administration, communication, analytics and personalized educational experiences through modern technology and AI.</p></div> }
function ResearchItem({ entry }) { return <article className="software-research-item education-item"><div className="software-research-meta"><span>Education</span><time>{entry.date}</time></div><div className="software-research-copy"><a href={`/education/${entry.slug}`}><h2>{entry.title}</h2><p>{entry.description}</p><StatusLabel status={entry.status} /></a></div></article> }
function ArchitectureBlock({ title, items }) { return <section className="education-block"><span className="section-label">{title}</span><div>{items.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item}</strong>{index < items.length - 1 && <i>↓</i>}</div>)}</div></section> }
function Capabilities() { const areas = [['Learning Management', 'Courses, content, assignments, assessments, schedules and learner progress.'], ['Student Systems', 'Student profiles, academic information, communication and engagement.'], ['Teacher Systems', 'Teacher workflows, course management, assignments, assessments and communication.'], ['AI Learning Assistant', 'AI-powered assistance for educational questions, content discovery and learning support.'], ['Personalized Learning', 'Adaptive recommendations and learning pathways based on available learner information.'], ['Communication', 'Notifications, announcements, reminders and communication across education communities.'], ['Automation', 'Automated academic and administrative workflows.'], ['Analytics & BI', 'Student, course, institution and operational analytics.']]; return <section className="education-capabilities"><span className="section-label">EDUCATION CAPABILITIES</span><div>{areas.map(([title, text]) => <div key={title}><h2>{title}</h2><p>{text}</p></div>)}</div></section> }
function Detail({ entry }) { return <section className="software-detail education-detail"><span className="section-label">EDUCATION / {entry.status}</span><h1>{entry.title}</h1><p>{entry.description}</p><StatusLabel status={entry.status} /><a className="button button-ghost" href="/education">Back to Education <span>↗</span></a></section> }

function EducationPage({ path = '/education' }) {
  useEffect(() => { const industriesButton = [...document.querySelectorAll('.site-header .nav-item')].find((button) => button.textContent.trim().startsWith('Industries')); industriesButton?.classList.add('active'); return () => industriesButton?.classList.remove('active') }, [])
  const entry = entries.find((item) => item.slug === path.split('/')[2])
  return <main className="rd-lab-page software-page education-page"><InternalNavigation /><section className="software-shell"><nav className="rd-lab-categories" aria-label="Education sections">{['All', 'Learning', 'AI', 'Automation', 'Analytics'].map((category, index) => <a className={index === 0 ? 'active' : ''} href="#publications" key={category}>{category}</a>)}</nav><ResearchHeader />{entry ? <Detail entry={entry} /> : <><div className="software-research-list" id="publications">{entries.map((item) => <ResearchItem entry={item} key={item.slug} />)}</div><ArchitectureBlock title="EDUCATION SYSTEM ARCHITECTURE" items={architecture} /><Capabilities /><ArchitectureBlock title="AI-POWERED EDUCATION" items={['AI LEARNING ASSISTANTS', 'EDUCATIONAL CONTENT ASSISTANCE', 'QUESTION ANSWERING', 'PERSONALIZED RECOMMENDATIONS', 'STUDY ASSISTANCE', 'TEACHER ASSISTANCE', 'ADMINISTRATIVE ASSISTANCE', 'EDUCATIONAL ANALYTICS']} /><ArchitectureBlock title="LEARNING JOURNEY / LEARNING FLOW" items={learningJourney} /><ArchitectureBlock title="EDUCATIONAL WORKFLOW AUTOMATION" items={automation} /><ArchitectureBlock title="LEARNING & INSTITUTIONAL INTELLIGENCE" items={analytics} /><ArchitectureBlock title="WEB & MOBILE EDUCATION PLATFORM" items={platform} /><ArchitectureBlock title="CONNECTED EDUCATION INFRASTRUCTURE" items={integration} /><ArchitectureBlock title="EDUCATION DATA & PRIVACY / SECURITY" items={['AUTHENTICATION', 'AUTHORIZATION', 'ROLE-BASED ACCESS', 'STUDENT-DATA PROTECTION', 'TEACHER PERMISSIONS', 'PARENT PERMISSIONS', 'API SECURITY', 'AUDIT LOGGING', 'BACKUPS', 'MONITORING', 'SECURE INTEGRATIONS']} /><ArchitectureBlock title="FUTURE OF EDUCATION TECHNOLOGY / FUTURE R&D" items={['AI LEARNING AGENTS', 'ADAPTIVE LEARNING SYSTEMS', 'PERSONALIZED EDUCATION', 'AI TEACHER ASSISTANTS', 'AI ADMINISTRATIVE ASSISTANTS', 'PREDICTIVE STUDENT SUPPORT', 'ADVANCED LEARNING ANALYTICS', 'MULTILINGUAL EDUCATION ASSISTANTS', 'VOICE-BASED LEARNING ASSISTANCE', 'INTELLIGENT EDUCATIONAL CONTENT', 'AI-POWERED INSTITUTIONAL INTELLIGENCE']} /></>}</section></main>
}

export default EducationPage
