import { useEffect } from 'react'
import { InternalNavigation } from './App.jsx'
import './SoftwareDevelopment.css'
import './OurApproach.css'

const stages = [
  { category: 'Research', title: 'Research First', description: 'Start with understanding the problem, opportunity, technology and requirements.', status: 'Research', slug: 'research' },
  { category: 'R&D', title: 'Experimentation', description: 'Explore ideas, models, architectures and possible solutions through experimentation.', status: 'Experiment', slug: 'experimentation' },
  { category: 'Architecture', title: 'System Design', description: 'Translate research into practical system architecture, software and technology.', status: 'Architecture', slug: 'architecture' },
  { category: 'Development', title: 'Build & Develop', description: 'Develop the required models, software, APIs, platforms and intelligent systems.', status: 'Development', slug: 'development' },
  { category: 'Validation', title: 'Test & Validate', description: 'Test prototypes, evaluate performance, learn from feedback and validate real-world scenarios.', status: 'Validation', slug: 'validation' },
  { category: 'Deployment', title: 'Real-World Deployment', description: 'Move validated technology into practical environments with integration, security and monitoring.', status: 'Deployment', slug: 'deployment' },
  { category: 'Innovation', title: 'Continuous Improvement', description: 'Research, measure, improve and continue evolving after deployment.', status: 'Continuous R&D', slug: 'continuous-r-and-d' },
]
const coreFlow = ['RESEARCH', 'UNDERSTAND', 'EXPERIMENT', 'DESIGN', 'BUILD', 'VALIDATE', 'DEPLOY', 'MEASURE', 'IMPROVE', 'RESEARCH AGAIN']
const continuousFlow = ['REAL-WORLD USAGE', 'DATA', 'FEEDBACK', 'ANALYSIS', 'RESEARCH', 'EXPERIMENTATION', 'IMPROVEMENT']
const businessFlow = ['BUSINESS PROBLEM', 'REQUIREMENTS', 'PROCESS ANALYSIS', 'TECHNOLOGY OPPORTUNITY', 'RESEARCH', 'EXPERIMENT', 'SOLUTION DESIGN', 'DEVELOPMENT', 'VALIDATION', 'DEPLOYMENT', 'BUSINESS IMPACT']
const rdLoop = ['QUESTION', 'RESEARCH', 'HYPOTHESIS', 'EXPERIMENT', 'RESULT', 'ANALYSIS', 'PROTOTYPE', 'SYSTEM', 'DEPLOYMENT', 'FEEDBACK', 'NEW QUESTION']

function StatusLabel({ status }) { return <span className="software-status">{status}</span> }
function ResearchHeader() { return <div className="software-research-header approach-header"><span className="section-label">OUR APPROACH</span><h1>Research. Build.<br /><em>Experiment. Deploy.</em></h1><p>A research-driven approach to artificial intelligence and technology development, combining continuous experimentation, system design, engineering, scalable platforms and real-world deployment.</p></div> }
function ResearchItem({ entry }) { return <article className="software-research-item approach-item"><div className="software-research-meta"><span>Our Approach</span><strong>{entry.category}</strong></div><div className="software-research-copy"><a href={`/our-approach/${entry.slug}`}><h2>{entry.title}</h2><p>{entry.description}</p><StatusLabel status={entry.status} /></a></div></article> }
function ProcessFlow({ title, items }) { return <section className="approach-flow"><span className="section-label">{title}</span><div>{items.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item}</strong>{index < items.length - 1 && <i>↓</i>}</div>)}</div></section> }
function StrategySection() { return <section className="approach-strategy"><span className="section-label">METHOD / TECHNOLOGY STRATEGY</span><h2>Right Technology for<br /><em>the Right Problem.</em></h2><p>Do not force a specific technology into every project. Evaluate the requirement first and choose the approach that belongs inside it.</p><div>{['Traditional software', 'APIs', 'Automation', 'Data systems', 'Machine learning', 'Generative AI', 'AI agents', 'Voice AI', 'RAG systems', 'Computer vision', 'Analytics', 'Custom technology'].map((item) => <span key={item}>{item}</span>)}</div><StatusLabel status="Technology Strategy" /></section> }
function HumanAI() { return <section className="approach-strategy"><span className="section-label">COLLABORATION</span><h2>Human + AI<br /><em>Collaboration.</em></h2><p>AI should augment human capabilities through assistance, analysis, automation, recommendations, retrieval and communication, with appropriate oversight for sensitive decisions.</p><div>{['Assistance', 'Analysis', 'Automation', 'Recommendations', 'Information retrieval', 'Communication', 'Repetitive work'].map((item) => <span key={item}>{item}</span>)}</div><StatusLabel status="AI" /></section> }
function Detail({ entry }) { return <section className="software-detail approach-detail"><span className="section-label">OUR APPROACH / {entry.status}</span><h1>{entry.title}</h1><p>{entry.description}</p><StatusLabel status={entry.status} /><a className="button button-ghost" href="/our-approach">Back to Our Approach <span>↗</span></a></section> }

function OurApproachPage({ path = '/our-approach' }) {
  useEffect(() => { const companyButton = [...document.querySelectorAll('.site-header .nav-item')].find((button) => button.textContent.trim().startsWith('Company')); companyButton?.classList.add('active'); return () => companyButton?.classList.remove('active') }, [])
  const entry = stages.find((item) => item.slug === path.split('/')[2])
  return <main className="rd-lab-page software-page approach-page"><InternalNavigation /><section className="software-shell"><ResearchHeader />{entry ? <Detail entry={entry} /> : <><div className="software-research-list">{stages.map((item) => <ResearchItem entry={item} key={item.slug} />)}</div><ProcessFlow title="CORE APPROACH / METHODOLOGY" items={coreFlow} /><section className="approach-note"><span className="section-label">RESEARCH</span><h2>Understand Before Building.</h2><p>Analyze requirements, workflows, systems, user needs, data, challenges, constraints and opportunities before selecting technology. Not every problem requires AI.</p><StatusLabel status="Research" /></section><section className="approach-note"><span className="section-label">EXPERIMENTATION</span><h2>Explore Before Scaling.</h2><p>Use prototypes, proofs of concept, model experiments, architecture experiments, workflow experiments and small-scale implementations before larger systems.</p><StatusLabel status="Experimentation" /></section><section className="approach-note"><span className="section-label">ARCHITECTURE</span><h2>Design for Scale.</h2><p>Design around modular architecture, APIs, databases, AI services, automation, integrations, authentication, security, monitoring and scalability.</p><StatusLabel status="Architecture" /></section><section className="approach-note"><span className="section-label">DEVELOPMENT</span><h2>Build Practical Systems.</h2><p>Turn validated concepts into software, AI systems, agents, platforms, APIs, automation, data systems and applications with maintainability in mind.</p><StatusLabel status="Development" /></section><section className="approach-note"><span className="section-label">VALIDATION</span><h2>Measure Before Expanding.</h2><p>Evaluate accuracy, reliability, performance, usability, operational impact, business value and scalability using measurable results.</p><StatusLabel status="Validation" /></section><section className="approach-note"><span className="section-label">DEPLOYMENT</span><h2>Move Into Reality.</h2><p>Deploy validated technology with infrastructure, security, integration, monitoring, documentation, user adoption and operational support.</p><StatusLabel status="Deployment" /></section><section className="approach-note"><span className="section-label">CONTINUOUS R&amp;D</span><h2>Never Stop Improving.</h2><p>Real-world usage creates data and feedback that drive analysis, research, experimentation and improvement.</p><StatusLabel status="R&D" /></section><StrategySection /><HumanAI /><ProcessFlow title="BUSINESS TO TECHNOLOGY / TRANSFORMATION" items={businessFlow} /><ProcessFlow title="RESEARCH & DEVELOPMENT LOOP / R&D" items={rdLoop} /><ProcessFlow title="CONTINUOUS DEVELOPMENT CYCLE" items={continuousFlow} /></>}</section></main>
}

export default OurApproachPage
